[package]
name = "amethyst-laminar-demo"
version = "0.1.0"
authors = ["surdom"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amethyst = "0.15.3"
log = "0.4.11"

[features]
default = ["amethyst/vulkan"]